### ISSUE TITLE
About the scenerio of two or more dynamic obstacles

### ISSUE THREAD

**Issue by feiyuxiaoThu** [pflab-ut/jerk_optimal_velocity_planning#1]
Congratulations on your newly-published work and  the idea of using LP instead of QP is nice. 
I find the proposed method was used to cope with scenerios like **Stopping** , **Vehicle Following** and **Cut-in Vehicle** and in all those scenerios only one dynamic obstacle is involved. So I am wondering how to extend your method to more complex scenerios like lane-changing into the gap between two vehicles, and thanks for your reply.

**Comment by purewater0901** [comment]
@feiyuxiaoThu Thank you for your comment, and sorry for being late to reply your message. As our paper said, our approach can only see one obstacle. However, we are improving our method to enable the algorithm to handle multiple obstacles.

**Comment by feiyuxiaoThu** [comment]
Thanks for your kind reply and looking forward to your further research.
